// Code generated by schema tool; DO NOT EDIT.

import * as wasmlib from 'wasmlib';
import * as wasmtypes from 'wasmlib/wasmtypes';

export class RussfestEvents {

    test(): void {
        const enc = wasmlib.eventEncoder('russfest.test');
        wasmlib.eventEmit(enc);
    }
}
