// Code generated by schema tool; DO NOT EDIT.

import * as wasmtypes from 'wasmlib/wasmtypes';
import * as sc from './index';

export class ImmutableAcceptShopParams extends wasmtypes.ScProxy {
    // Name of the Shop
    shopName(): wasmtypes.ScImmutableString {
        return new wasmtypes.ScImmutableString(this.proxy.root(sc.ParamShopName));
    }
}

export class MutableAcceptShopParams extends wasmtypes.ScProxy {
    // Name of the Shop
    shopName(): wasmtypes.ScMutableString {
        return new wasmtypes.ScMutableString(this.proxy.root(sc.ParamShopName));
    }
}

export class ImmutableAddMusicianParams extends wasmtypes.ScProxy {
    // name of musician
    name(): wasmtypes.ScImmutableString {
        return new wasmtypes.ScImmutableString(this.proxy.root(sc.ParamName));
    }

    // optional shop for merch
    shop(): wasmtypes.ScImmutableString {
        return new wasmtypes.ScImmutableString(this.proxy.root(sc.ParamShop));
    }
}

export class MutableAddMusicianParams extends wasmtypes.ScProxy {
    // name of musician
    name(): wasmtypes.ScMutableString {
        return new wasmtypes.ScMutableString(this.proxy.root(sc.ParamName));
    }

    // optional shop for merch
    shop(): wasmtypes.ScMutableString {
        return new wasmtypes.ScMutableString(this.proxy.root(sc.ParamShop));
    }
}

export class ImmutableBuyMerchParams extends wasmtypes.ScProxy {
    // Musician
    musician(): wasmtypes.ScImmutableString {
        return new wasmtypes.ScImmutableString(this.proxy.root(sc.ParamMusician));
    }

    // type of Product
    productType(): wasmtypes.ScImmutableString {
        return new wasmtypes.ScImmutableString(this.proxy.root(sc.ParamProductType));
    }

    // Name of the shop
    shopName(): wasmtypes.ScImmutableString {
        return new wasmtypes.ScImmutableString(this.proxy.root(sc.ParamShopName));
    }
}

export class MutableBuyMerchParams extends wasmtypes.ScProxy {
    // Musician
    musician(): wasmtypes.ScMutableString {
        return new wasmtypes.ScMutableString(this.proxy.root(sc.ParamMusician));
    }

    // type of Product
    productType(): wasmtypes.ScMutableString {
        return new wasmtypes.ScMutableString(this.proxy.root(sc.ParamProductType));
    }

    // Name of the shop
    shopName(): wasmtypes.ScMutableString {
        return new wasmtypes.ScMutableString(this.proxy.root(sc.ParamShopName));
    }
}

export class ImmutableCallCheckProductParams extends wasmtypes.ScProxy {
    // Product I want to check
    product(): sc.ImmutableProductTemplate {
        return new sc.ImmutableProductTemplate(this.proxy.root(sc.ParamProduct));
    }
}

export class MutableCallCheckProductParams extends wasmtypes.ScProxy {
    // Product I want to check
    product(): sc.MutableProductTemplate {
        return new sc.MutableProductTemplate(this.proxy.root(sc.ParamProduct));
    }
}

export class ImmutableCallCreateNewProductParams extends wasmtypes.ScProxy {
    // name of musician
    musicianName(): wasmtypes.ScImmutableString {
        return new wasmtypes.ScImmutableString(this.proxy.root(sc.ParamMusicianName));
    }

    // Price of product
    price(): wasmtypes.ScImmutableUint64 {
        return new wasmtypes.ScImmutableUint64(this.proxy.root(sc.ParamPrice));
    }

    // type of Product e.g. Tshirt
    productType(): wasmtypes.ScImmutableString {
        return new wasmtypes.ScImmutableString(this.proxy.root(sc.ParamProductType));
    }

    // name of the Shop
    shopName(): wasmtypes.ScImmutableString {
        return new wasmtypes.ScImmutableString(this.proxy.root(sc.ParamShopName));
    }
}

export class MutableCallCreateNewProductParams extends wasmtypes.ScProxy {
    // name of musician
    musicianName(): wasmtypes.ScMutableString {
        return new wasmtypes.ScMutableString(this.proxy.root(sc.ParamMusicianName));
    }

    // Price of product
    price(): wasmtypes.ScMutableUint64 {
        return new wasmtypes.ScMutableUint64(this.proxy.root(sc.ParamPrice));
    }

    // type of Product e.g. Tshirt
    productType(): wasmtypes.ScMutableString {
        return new wasmtypes.ScMutableString(this.proxy.root(sc.ParamProductType));
    }

    // name of the Shop
    shopName(): wasmtypes.ScMutableString {
        return new wasmtypes.ScMutableString(this.proxy.root(sc.ParamShopName));
    }
}

export class ImmutableCallPayStoreParams extends wasmtypes.ScProxy {
    // name of the shop
    shopName(): wasmtypes.ScImmutableString {
        return new wasmtypes.ScImmutableString(this.proxy.root(sc.ParamShopName));
    }
}

export class MutableCallPayStoreParams extends wasmtypes.ScProxy {
    // name of the shop
    shopName(): wasmtypes.ScMutableString {
        return new wasmtypes.ScMutableString(this.proxy.root(sc.ParamShopName));
    }
}

export class ImmutableCancelShopRequestParams extends wasmtypes.ScProxy {
    // Name of the Shop
    name(): wasmtypes.ScImmutableString {
        return new wasmtypes.ScImmutableString(this.proxy.root(sc.ParamName));
    }
}

export class MutableCancelShopRequestParams extends wasmtypes.ScProxy {
    // Name of the Shop
    name(): wasmtypes.ScMutableString {
        return new wasmtypes.ScMutableString(this.proxy.root(sc.ParamName));
    }
}

export class ImmutableDenyShopParams extends wasmtypes.ScProxy {
    // Name of the Shop
    shopName(): wasmtypes.ScImmutableString {
        return new wasmtypes.ScImmutableString(this.proxy.root(sc.ParamShopName));
    }
}

export class MutableDenyShopParams extends wasmtypes.ScProxy {
    // Name of the Shop
    shopName(): wasmtypes.ScMutableString {
        return new wasmtypes.ScMutableString(this.proxy.root(sc.ParamShopName));
    }
}

export class ImmutableInitParams extends wasmtypes.ScProxy {
    // optional owner of this smart contract
    owner(): wasmtypes.ScImmutableAgentID {
        return new wasmtypes.ScImmutableAgentID(this.proxy.root(sc.ParamOwner));
    }
}

export class MutableInitParams extends wasmtypes.ScProxy {
    // optional owner of this smart contract
    owner(): wasmtypes.ScMutableAgentID {
        return new wasmtypes.ScMutableAgentID(this.proxy.root(sc.ParamOwner));
    }
}

export class ImmutableRequestShopLicenceParams extends wasmtypes.ScProxy {
    // fee to pay
    fee(): wasmtypes.ScImmutableUint64 {
        return new wasmtypes.ScImmutableUint64(this.proxy.root(sc.ParamFee));
    }

    // Name of the Musician
    musicianName(): wasmtypes.ScImmutableString {
        return new wasmtypes.ScImmutableString(this.proxy.root(sc.ParamMusicianName));
    }

    // Name of the Shop
    name(): wasmtypes.ScImmutableString {
        return new wasmtypes.ScImmutableString(this.proxy.root(sc.ParamName));
    }

    // hname of Shop
    shopHname(): wasmtypes.ScImmutableHname {
        return new wasmtypes.ScImmutableHname(this.proxy.root(sc.ParamShopHname));
    }
}

export class MutableRequestShopLicenceParams extends wasmtypes.ScProxy {
    // fee to pay
    fee(): wasmtypes.ScMutableUint64 {
        return new wasmtypes.ScMutableUint64(this.proxy.root(sc.ParamFee));
    }

    // Name of the Musician
    musicianName(): wasmtypes.ScMutableString {
        return new wasmtypes.ScMutableString(this.proxy.root(sc.ParamMusicianName));
    }

    // Name of the Shop
    name(): wasmtypes.ScMutableString {
        return new wasmtypes.ScMutableString(this.proxy.root(sc.ParamName));
    }

    // hname of Shop
    shopHname(): wasmtypes.ScMutableHname {
        return new wasmtypes.ScMutableHname(this.proxy.root(sc.ParamShopHname));
    }
}

export class ImmutableSetOwnerParams extends wasmtypes.ScProxy {
    // new owner of this smart contract
    newOwner(): wasmtypes.ScImmutableAgentID {
        return new wasmtypes.ScImmutableAgentID(this.proxy.root(sc.ParamNewOwner));
    }
}

export class MutableSetOwnerParams extends wasmtypes.ScProxy {
    // new owner of this smart contract
    newOwner(): wasmtypes.ScMutableAgentID {
        return new wasmtypes.ScMutableAgentID(this.proxy.root(sc.ParamNewOwner));
    }
}

export class ImmutableUpdateDeniedShopRequestParams extends wasmtypes.ScProxy {
    // fee to pay
    newfee(): wasmtypes.ScImmutableUint64 {
        return new wasmtypes.ScImmutableUint64(this.proxy.root(sc.ParamNewfee));
    }

    // new Hname of Address
    newHname(): wasmtypes.ScImmutableHname {
        return new wasmtypes.ScImmutableHname(this.proxy.root(sc.ParamNewHname));
    }

    // Name of the Shop
    shopName(): wasmtypes.ScImmutableString {
        return new wasmtypes.ScImmutableString(this.proxy.root(sc.ParamShopName));
    }
}

export class MutableUpdateDeniedShopRequestParams extends wasmtypes.ScProxy {
    // fee to pay
    newfee(): wasmtypes.ScMutableUint64 {
        return new wasmtypes.ScMutableUint64(this.proxy.root(sc.ParamNewfee));
    }

    // new Hname of Address
    newHname(): wasmtypes.ScMutableHname {
        return new wasmtypes.ScMutableHname(this.proxy.root(sc.ParamNewHname));
    }

    // Name of the Shop
    shopName(): wasmtypes.ScMutableString {
        return new wasmtypes.ScMutableString(this.proxy.root(sc.ParamShopName));
    }
}

export class ImmutableCallGetShopStatisticsParams extends wasmtypes.ScProxy {
    // name of the shop
    shopName(): wasmtypes.ScImmutableString {
        return new wasmtypes.ScImmutableString(this.proxy.root(sc.ParamShopName));
    }
}

export class MutableCallGetShopStatisticsParams extends wasmtypes.ScProxy {
    // name of the shop
    shopName(): wasmtypes.ScMutableString {
        return new wasmtypes.ScMutableString(this.proxy.root(sc.ParamShopName));
    }
}

export class ImmutableGetDeniedShopRequestsParams extends wasmtypes.ScProxy {
    // ID of shop Owner
    shopOwner(): wasmtypes.ScImmutableAgentID {
        return new wasmtypes.ScImmutableAgentID(this.proxy.root(sc.ParamShopOwner));
    }
}

export class MutableGetDeniedShopRequestsParams extends wasmtypes.ScProxy {
    // ID of shop Owner
    shopOwner(): wasmtypes.ScMutableAgentID {
        return new wasmtypes.ScMutableAgentID(this.proxy.root(sc.ParamShopOwner));
    }
}

export class ImmutableGetErrorMessagesViewParams extends wasmtypes.ScProxy {
    // string of requestID
    requestID(): wasmtypes.ScImmutableString {
        return new wasmtypes.ScImmutableString(this.proxy.root(sc.ParamRequestID));
    }
}

export class MutableGetErrorMessagesViewParams extends wasmtypes.ScProxy {
    // string of requestID
    requestID(): wasmtypes.ScMutableString {
        return new wasmtypes.ScMutableString(this.proxy.root(sc.ParamRequestID));
    }
}

export class ImmutableGetOpenShopRequestParams extends wasmtypes.ScProxy {
    // agendID of owner
    shopOwner(): wasmtypes.ScImmutableAgentID {
        return new wasmtypes.ScImmutableAgentID(this.proxy.root(sc.ParamShopOwner));
    }
}

export class MutableGetOpenShopRequestParams extends wasmtypes.ScProxy {
    // agendID of owner
    shopOwner(): wasmtypes.ScMutableAgentID {
        return new wasmtypes.ScMutableAgentID(this.proxy.root(sc.ParamShopOwner));
    }
}

export class ImmutableGetRegisteredShopsFromOwnerParams extends wasmtypes.ScProxy {
    // agentID from owner
    shopOwner(): wasmtypes.ScImmutableAgentID {
        return new wasmtypes.ScImmutableAgentID(this.proxy.root(sc.ParamShopOwner));
    }
}

export class MutableGetRegisteredShopsFromOwnerParams extends wasmtypes.ScProxy {
    // agentID from owner
    shopOwner(): wasmtypes.ScMutableAgentID {
        return new wasmtypes.ScMutableAgentID(this.proxy.root(sc.ParamShopOwner));
    }
}

export class ImmutableGetShopStatisticsParams extends wasmtypes.ScProxy {
    // name of the shop
    shopName(): wasmtypes.ScImmutableString {
        return new wasmtypes.ScImmutableString(this.proxy.root(sc.ParamShopName));
    }
}

export class MutableGetShopStatisticsParams extends wasmtypes.ScProxy {
    // name of the shop
    shopName(): wasmtypes.ScMutableString {
        return new wasmtypes.ScMutableString(this.proxy.root(sc.ParamShopName));
    }
}

export class ImmutableGetSpecificProductsParams extends wasmtypes.ScProxy {
    // Name of Musician
    shopName(): wasmtypes.ScImmutableString {
        return new wasmtypes.ScImmutableString(this.proxy.root(sc.ParamShopName));
    }
}

export class MutableGetSpecificProductsParams extends wasmtypes.ScProxy {
    // Name of Musician
    shopName(): wasmtypes.ScMutableString {
        return new wasmtypes.ScMutableString(this.proxy.root(sc.ParamShopName));
    }
}
