// Code generated by schema tool; DO NOT EDIT.

#![allow(dead_code)]
#![allow(unused_mut)]

use wasmlib::*;

pub struct RussfestEvents {
}

impl RussfestEvents {

	pub fn test(&self) {
		let mut enc = EventEncoder::new("russfest.test");
		EventEncoder::emit(&enc);
	}
}
