// Code generated by schema tool; DO NOT EDIT.

#![allow(dead_code)]

use wasmlib::*;

pub const SC_NAME        : &str = "shop1";
pub const SC_DESCRIPTION : &str = "shop1 description";
pub const HSC_NAME       : ScHname = ScHname(0xd2edc375);

pub const PARAM_MUSICIAN_NAME : &str = "musicianName";
pub const PARAM_OWNER         : &str = "owner";
pub const PARAM_PRICE         : &str = "price";
pub const PARAM_PRODUCT       : &str = "product";
pub const PARAM_PRODUCT_TYPE  : &str = "productType";
pub const PARAM_SHOP_NAME     : &str = "shopName";

pub const RESULT_CAN_PRODUCE                  : &str = "canProduce";
pub const RESULT_EARNINGS                     : &str = "earnings";
pub const RESULT_EARNINGS_PER_SHOP            : &str = "earningsPerShop";
pub const RESULT_MAX_PRODUCTIONS_STEP         : &str = "maxProductionsStep";
pub const RESULT_MAX_PRODUCTION_STEPS         : &str = "maxProductionSteps";
pub const RESULT_MESSAGE                      : &str = "message";
pub const RESULT_OWNER                        : &str = "owner";
pub const RESULT_PING_SUCCESSFUL              : &str = "pingSuccessful";
pub const RESULT_PRODUCED_PRODUCTS            : &str = "producedProducts";
pub const RESULT_PRODUCED_PRODUCTS_PER_SHOP   : &str = "producedProductsPerShop";
pub const RESULT_PRODUCT                      : &str = "product";
pub const RESULT_PRODUCTION                   : &str = "production";
pub const RESULT_PRODUCTION_TEMPLATES         : &str = "productionTemplates";
pub const RESULT_PRODUCTS_IN_PRODUCTION       : &str = "productsInProduction";
pub const RESULT_SOLD_PRODUCTS                : &str = "soldProducts";
pub const RESULT_SOLD_PRODUCTS_PER_SHOP       : &str = "soldProductsPerShop";
pub const RESULT_TOTAL_EARNINGS               : &str = "totalEarnings";
pub const RESULT_TOTAL_PRODUCED_PRODUCTS      : &str = "totalProducedProducts";
pub const RESULT_TOTAL_PRODUCTS_IN_PRODUCTION : &str = "totalProductsInProduction";
pub const RESULT_TOTAL_SOLD_PRODUCTS          : &str = "totalSoldProducts";

pub const STATE_EARNED_MONEY            : &str = "earnedMoney";
pub const STATE_FESTIVAL_HNAME          : &str = "festivalHname";
pub const STATE_FINISHED_PRODUCTS       : &str = "finishedProducts";
pub const STATE_OWNER                   : &str = "owner";
pub const STATE_PRODUCED_PRODUCTS       : &str = "producedProducts";
pub const STATE_PRODUCING_PRODUCTS      : &str = "producingProducts";
pub const STATE_PRODUCT_ID              : &str = "productID";
pub const STATE_PRODUCT_TEMPLATES       : &str = "productTemplates";
pub const STATE_SHOP_NAMES              : &str = "shopNames";
pub const STATE_SOLD_PRODUCTS           : &str = "soldProducts";
pub const STATE_TOTAL_EARNED_MONEY      : &str = "totalEarnedMoney";
pub const STATE_TOTAL_PRODUCED_PRODUCTS : &str = "totalProducedProducts";
pub const STATE_TOTAL_SOLD_PRODUCTS     : &str = "totalSoldProducts";

pub const FUNC_CALL_CHECK_PRODUCT         : &str = "callCheckProduct";
pub const FUNC_CALL_CREATE_NEW_PRODUCT    : &str = "callCreateNewProduct";
pub const FUNC_CALL_PAY_STORE             : &str = "callPayStore";
pub const FUNC_CALL_PING_SHOP             : &str = "callPingShop";
pub const FUNC_CALL_RECIEVE_PRODUCTS      : &str = "callRecieveProducts";
pub const FUNC_CALL_SEND_PRODUCT          : &str = "callSendProduct";
pub const FUNC_INIT                       : &str = "init";
pub const FUNC_PRODUCE                    : &str = "produce";
pub const FUNC_SET_OWNER                  : &str = "setOwner";
pub const FUNC_START_PRODUCTION           : &str = "startProduction";
pub const VIEW_CALL_GET_SHOP_STATISTICS   : &str = "callGetShopStatistics";
pub const VIEW_GET_EARNINGS               : &str = "getEarnings";
pub const VIEW_GET_MAX_PRODUCTION_STEPS   : &str = "getMaxProductionSteps";
pub const VIEW_GET_OWNER                  : &str = "getOwner";
pub const VIEW_GET_PRODUCED_PRODUCTS      : &str = "getProducedProducts";
pub const VIEW_GET_PRODUCTS_IN_PRODUCTION : &str = "getProductsInProduction";
pub const VIEW_GET_SOLD_PRODUCTS          : &str = "getSoldProducts";

pub const HFUNC_CALL_CHECK_PRODUCT         : ScHname = ScHname(0xdfd91d1f);
pub const HFUNC_CALL_CREATE_NEW_PRODUCT    : ScHname = ScHname(0xaf42fee4);
pub const HFUNC_CALL_PAY_STORE             : ScHname = ScHname(0xc8ab38d7);
pub const HFUNC_CALL_PING_SHOP             : ScHname = ScHname(0xc6022857);
pub const HFUNC_CALL_RECIEVE_PRODUCTS      : ScHname = ScHname(0x7e74c00e);
pub const HFUNC_CALL_SEND_PRODUCT          : ScHname = ScHname(0x36c3773f);
pub const HFUNC_INIT                       : ScHname = ScHname(0x1f44d644);
pub const HFUNC_PRODUCE                    : ScHname = ScHname(0xa01d4f7d);
pub const HFUNC_SET_OWNER                  : ScHname = ScHname(0x2a15fe7b);
pub const HFUNC_START_PRODUCTION           : ScHname = ScHname(0x73a9f710);
pub const HVIEW_CALL_GET_SHOP_STATISTICS   : ScHname = ScHname(0x52d265ae);
pub const HVIEW_GET_EARNINGS               : ScHname = ScHname(0xe544381a);
pub const HVIEW_GET_MAX_PRODUCTION_STEPS   : ScHname = ScHname(0xe5f0b61c);
pub const HVIEW_GET_OWNER                  : ScHname = ScHname(0x137107a6);
pub const HVIEW_GET_PRODUCED_PRODUCTS      : ScHname = ScHname(0x9e660552);
pub const HVIEW_GET_PRODUCTS_IN_PRODUCTION : ScHname = ScHname(0x0b4a8e05);
pub const HVIEW_GET_SOLD_PRODUCTS          : ScHname = ScHname(0x7d013762);
