// Code generated by schema tool; DO NOT EDIT.

package russfest

import (
	"github.com/iotaledger/wasp/packages/wasmvm/wasmlib/go/wasmlib"
	"github.com/iotaledger/wasp/packages/wasmvm/wasmlib/go/wasmlib/wasmtypes"
)

type RussfestEvents struct{}

func (e RussfestEvents) Test() {
	enc := wasmlib.NewEventEncoder("russfest.test")
	wasmlib.EventEmit(enc)
}
