// Code generated by schema tool; DO NOT EDIT.

package russfest

import (
	"github.com/iotaledger/wasp/packages/wasmvm/wasmlib/go/wasmlib"
	"github.com/iotaledger/wasp/packages/wasmvm/wasmlib/go/wasmlib/wasmtypes"
)

type ImmutableAcceptShopParams struct {
	Proxy wasmtypes.Proxy
}

func NewImmutableAcceptShopParams() ImmutableAcceptShopParams {
	return ImmutableAcceptShopParams{Proxy: wasmlib.NewParamsProxy()}
}

// Name of the Shop
func (s ImmutableAcceptShopParams) ShopName() wasmtypes.ScImmutableString {
	return wasmtypes.NewScImmutableString(s.Proxy.Root(ParamShopName))
}

type MutableAcceptShopParams struct {
	Proxy wasmtypes.Proxy
}

// Name of the Shop
func (s MutableAcceptShopParams) ShopName() wasmtypes.ScMutableString {
	return wasmtypes.NewScMutableString(s.Proxy.Root(ParamShopName))
}

type ImmutableAddMusicianParams struct {
	Proxy wasmtypes.Proxy
}

func NewImmutableAddMusicianParams() ImmutableAddMusicianParams {
	return ImmutableAddMusicianParams{Proxy: wasmlib.NewParamsProxy()}
}

// name of musician
func (s ImmutableAddMusicianParams) Name() wasmtypes.ScImmutableString {
	return wasmtypes.NewScImmutableString(s.Proxy.Root(ParamName))
}

// optional shop for merch
func (s ImmutableAddMusicianParams) Shop() wasmtypes.ScImmutableString {
	return wasmtypes.NewScImmutableString(s.Proxy.Root(ParamShop))
}

type MutableAddMusicianParams struct {
	Proxy wasmtypes.Proxy
}

// name of musician
func (s MutableAddMusicianParams) Name() wasmtypes.ScMutableString {
	return wasmtypes.NewScMutableString(s.Proxy.Root(ParamName))
}

// optional shop for merch
func (s MutableAddMusicianParams) Shop() wasmtypes.ScMutableString {
	return wasmtypes.NewScMutableString(s.Proxy.Root(ParamShop))
}

type ImmutableBuyMerchParams struct {
	Proxy wasmtypes.Proxy
}

func NewImmutableBuyMerchParams() ImmutableBuyMerchParams {
	return ImmutableBuyMerchParams{Proxy: wasmlib.NewParamsProxy()}
}

// Musician
func (s ImmutableBuyMerchParams) Musician() wasmtypes.ScImmutableString {
	return wasmtypes.NewScImmutableString(s.Proxy.Root(ParamMusician))
}

// type of Product
func (s ImmutableBuyMerchParams) ProductType() wasmtypes.ScImmutableString {
	return wasmtypes.NewScImmutableString(s.Proxy.Root(ParamProductType))
}

// Name of the shop
func (s ImmutableBuyMerchParams) ShopName() wasmtypes.ScImmutableString {
	return wasmtypes.NewScImmutableString(s.Proxy.Root(ParamShopName))
}

type MutableBuyMerchParams struct {
	Proxy wasmtypes.Proxy
}

// Musician
func (s MutableBuyMerchParams) Musician() wasmtypes.ScMutableString {
	return wasmtypes.NewScMutableString(s.Proxy.Root(ParamMusician))
}

// type of Product
func (s MutableBuyMerchParams) ProductType() wasmtypes.ScMutableString {
	return wasmtypes.NewScMutableString(s.Proxy.Root(ParamProductType))
}

// Name of the shop
func (s MutableBuyMerchParams) ShopName() wasmtypes.ScMutableString {
	return wasmtypes.NewScMutableString(s.Proxy.Root(ParamShopName))
}

type ImmutableCallCheckProductParams struct {
	Proxy wasmtypes.Proxy
}

func NewImmutableCallCheckProductParams() ImmutableCallCheckProductParams {
	return ImmutableCallCheckProductParams{Proxy: wasmlib.NewParamsProxy()}
}

// Product I want to check
func (s ImmutableCallCheckProductParams) Product() ImmutableProductTemplate {
	return ImmutableProductTemplate{Proxy: s.Proxy.Root(ParamProduct)}
}

type MutableCallCheckProductParams struct {
	Proxy wasmtypes.Proxy
}

// Product I want to check
func (s MutableCallCheckProductParams) Product() MutableProductTemplate {
	return MutableProductTemplate{Proxy: s.Proxy.Root(ParamProduct)}
}

type ImmutableCallCreateNewProductParams struct {
	Proxy wasmtypes.Proxy
}

func NewImmutableCallCreateNewProductParams() ImmutableCallCreateNewProductParams {
	return ImmutableCallCreateNewProductParams{Proxy: wasmlib.NewParamsProxy()}
}

// name of musician
func (s ImmutableCallCreateNewProductParams) MusicianName() wasmtypes.ScImmutableString {
	return wasmtypes.NewScImmutableString(s.Proxy.Root(ParamMusicianName))
}

// Price of product
func (s ImmutableCallCreateNewProductParams) Price() wasmtypes.ScImmutableUint64 {
	return wasmtypes.NewScImmutableUint64(s.Proxy.Root(ParamPrice))
}

// type of Product e.g. Tshirt
func (s ImmutableCallCreateNewProductParams) ProductType() wasmtypes.ScImmutableString {
	return wasmtypes.NewScImmutableString(s.Proxy.Root(ParamProductType))
}

// name of the Shop
func (s ImmutableCallCreateNewProductParams) ShopName() wasmtypes.ScImmutableString {
	return wasmtypes.NewScImmutableString(s.Proxy.Root(ParamShopName))
}

type MutableCallCreateNewProductParams struct {
	Proxy wasmtypes.Proxy
}

// name of musician
func (s MutableCallCreateNewProductParams) MusicianName() wasmtypes.ScMutableString {
	return wasmtypes.NewScMutableString(s.Proxy.Root(ParamMusicianName))
}

// Price of product
func (s MutableCallCreateNewProductParams) Price() wasmtypes.ScMutableUint64 {
	return wasmtypes.NewScMutableUint64(s.Proxy.Root(ParamPrice))
}

// type of Product e.g. Tshirt
func (s MutableCallCreateNewProductParams) ProductType() wasmtypes.ScMutableString {
	return wasmtypes.NewScMutableString(s.Proxy.Root(ParamProductType))
}

// name of the Shop
func (s MutableCallCreateNewProductParams) ShopName() wasmtypes.ScMutableString {
	return wasmtypes.NewScMutableString(s.Proxy.Root(ParamShopName))
}

type ImmutableCallPayStoreParams struct {
	Proxy wasmtypes.Proxy
}

func NewImmutableCallPayStoreParams() ImmutableCallPayStoreParams {
	return ImmutableCallPayStoreParams{Proxy: wasmlib.NewParamsProxy()}
}

// name of the shop
func (s ImmutableCallPayStoreParams) ShopName() wasmtypes.ScImmutableString {
	return wasmtypes.NewScImmutableString(s.Proxy.Root(ParamShopName))
}

type MutableCallPayStoreParams struct {
	Proxy wasmtypes.Proxy
}

// name of the shop
func (s MutableCallPayStoreParams) ShopName() wasmtypes.ScMutableString {
	return wasmtypes.NewScMutableString(s.Proxy.Root(ParamShopName))
}

type ImmutableCancelShopRequestParams struct {
	Proxy wasmtypes.Proxy
}

func NewImmutableCancelShopRequestParams() ImmutableCancelShopRequestParams {
	return ImmutableCancelShopRequestParams{Proxy: wasmlib.NewParamsProxy()}
}

// Name of the Shop
func (s ImmutableCancelShopRequestParams) Name() wasmtypes.ScImmutableString {
	return wasmtypes.NewScImmutableString(s.Proxy.Root(ParamName))
}

type MutableCancelShopRequestParams struct {
	Proxy wasmtypes.Proxy
}

// Name of the Shop
func (s MutableCancelShopRequestParams) Name() wasmtypes.ScMutableString {
	return wasmtypes.NewScMutableString(s.Proxy.Root(ParamName))
}

type ImmutableDenyShopParams struct {
	Proxy wasmtypes.Proxy
}

func NewImmutableDenyShopParams() ImmutableDenyShopParams {
	return ImmutableDenyShopParams{Proxy: wasmlib.NewParamsProxy()}
}

// Name of the Shop
func (s ImmutableDenyShopParams) ShopName() wasmtypes.ScImmutableString {
	return wasmtypes.NewScImmutableString(s.Proxy.Root(ParamShopName))
}

type MutableDenyShopParams struct {
	Proxy wasmtypes.Proxy
}

// Name of the Shop
func (s MutableDenyShopParams) ShopName() wasmtypes.ScMutableString {
	return wasmtypes.NewScMutableString(s.Proxy.Root(ParamShopName))
}

type ImmutableInitParams struct {
	Proxy wasmtypes.Proxy
}

func NewImmutableInitParams() ImmutableInitParams {
	return ImmutableInitParams{Proxy: wasmlib.NewParamsProxy()}
}

// optional owner of this smart contract
func (s ImmutableInitParams) Owner() wasmtypes.ScImmutableAgentID {
	return wasmtypes.NewScImmutableAgentID(s.Proxy.Root(ParamOwner))
}

type MutableInitParams struct {
	Proxy wasmtypes.Proxy
}

// optional owner of this smart contract
func (s MutableInitParams) Owner() wasmtypes.ScMutableAgentID {
	return wasmtypes.NewScMutableAgentID(s.Proxy.Root(ParamOwner))
}

type ImmutableRequestShopLicenceParams struct {
	Proxy wasmtypes.Proxy
}

func NewImmutableRequestShopLicenceParams() ImmutableRequestShopLicenceParams {
	return ImmutableRequestShopLicenceParams{Proxy: wasmlib.NewParamsProxy()}
}

// fee to pay
func (s ImmutableRequestShopLicenceParams) Fee() wasmtypes.ScImmutableUint64 {
	return wasmtypes.NewScImmutableUint64(s.Proxy.Root(ParamFee))
}

// Name of the Musician
func (s ImmutableRequestShopLicenceParams) MusicianName() wasmtypes.ScImmutableString {
	return wasmtypes.NewScImmutableString(s.Proxy.Root(ParamMusicianName))
}

// Name of the Shop
func (s ImmutableRequestShopLicenceParams) Name() wasmtypes.ScImmutableString {
	return wasmtypes.NewScImmutableString(s.Proxy.Root(ParamName))
}

// hname of Shop
func (s ImmutableRequestShopLicenceParams) ShopHname() wasmtypes.ScImmutableHname {
	return wasmtypes.NewScImmutableHname(s.Proxy.Root(ParamShopHname))
}

type MutableRequestShopLicenceParams struct {
	Proxy wasmtypes.Proxy
}

// fee to pay
func (s MutableRequestShopLicenceParams) Fee() wasmtypes.ScMutableUint64 {
	return wasmtypes.NewScMutableUint64(s.Proxy.Root(ParamFee))
}

// Name of the Musician
func (s MutableRequestShopLicenceParams) MusicianName() wasmtypes.ScMutableString {
	return wasmtypes.NewScMutableString(s.Proxy.Root(ParamMusicianName))
}

// Name of the Shop
func (s MutableRequestShopLicenceParams) Name() wasmtypes.ScMutableString {
	return wasmtypes.NewScMutableString(s.Proxy.Root(ParamName))
}

// hname of Shop
func (s MutableRequestShopLicenceParams) ShopHname() wasmtypes.ScMutableHname {
	return wasmtypes.NewScMutableHname(s.Proxy.Root(ParamShopHname))
}

type ImmutableSetOwnerParams struct {
	Proxy wasmtypes.Proxy
}

func NewImmutableSetOwnerParams() ImmutableSetOwnerParams {
	return ImmutableSetOwnerParams{Proxy: wasmlib.NewParamsProxy()}
}

// new owner of this smart contract
func (s ImmutableSetOwnerParams) NewOwner() wasmtypes.ScImmutableAgentID {
	return wasmtypes.NewScImmutableAgentID(s.Proxy.Root(ParamNewOwner))
}

type MutableSetOwnerParams struct {
	Proxy wasmtypes.Proxy
}

// new owner of this smart contract
func (s MutableSetOwnerParams) NewOwner() wasmtypes.ScMutableAgentID {
	return wasmtypes.NewScMutableAgentID(s.Proxy.Root(ParamNewOwner))
}

type ImmutableUpdateDeniedShopRequestParams struct {
	Proxy wasmtypes.Proxy
}

func NewImmutableUpdateDeniedShopRequestParams() ImmutableUpdateDeniedShopRequestParams {
	return ImmutableUpdateDeniedShopRequestParams{Proxy: wasmlib.NewParamsProxy()}
}

// fee to pay
func (s ImmutableUpdateDeniedShopRequestParams) Newfee() wasmtypes.ScImmutableUint64 {
	return wasmtypes.NewScImmutableUint64(s.Proxy.Root(ParamNewfee))
}

// new Hname of Address
func (s ImmutableUpdateDeniedShopRequestParams) NewHname() wasmtypes.ScImmutableHname {
	return wasmtypes.NewScImmutableHname(s.Proxy.Root(ParamNewHname))
}

// Name of the Shop
func (s ImmutableUpdateDeniedShopRequestParams) ShopName() wasmtypes.ScImmutableString {
	return wasmtypes.NewScImmutableString(s.Proxy.Root(ParamShopName))
}

type MutableUpdateDeniedShopRequestParams struct {
	Proxy wasmtypes.Proxy
}

// fee to pay
func (s MutableUpdateDeniedShopRequestParams) Newfee() wasmtypes.ScMutableUint64 {
	return wasmtypes.NewScMutableUint64(s.Proxy.Root(ParamNewfee))
}

// new Hname of Address
func (s MutableUpdateDeniedShopRequestParams) NewHname() wasmtypes.ScMutableHname {
	return wasmtypes.NewScMutableHname(s.Proxy.Root(ParamNewHname))
}

// Name of the Shop
func (s MutableUpdateDeniedShopRequestParams) ShopName() wasmtypes.ScMutableString {
	return wasmtypes.NewScMutableString(s.Proxy.Root(ParamShopName))
}

type ImmutableCallGetShopStatisticsParams struct {
	Proxy wasmtypes.Proxy
}

func NewImmutableCallGetShopStatisticsParams() ImmutableCallGetShopStatisticsParams {
	return ImmutableCallGetShopStatisticsParams{Proxy: wasmlib.NewParamsProxy()}
}

// name of the shop
func (s ImmutableCallGetShopStatisticsParams) ShopName() wasmtypes.ScImmutableString {
	return wasmtypes.NewScImmutableString(s.Proxy.Root(ParamShopName))
}

type MutableCallGetShopStatisticsParams struct {
	Proxy wasmtypes.Proxy
}

// name of the shop
func (s MutableCallGetShopStatisticsParams) ShopName() wasmtypes.ScMutableString {
	return wasmtypes.NewScMutableString(s.Proxy.Root(ParamShopName))
}

type ImmutableGetDeniedShopRequestsParams struct {
	Proxy wasmtypes.Proxy
}

func NewImmutableGetDeniedShopRequestsParams() ImmutableGetDeniedShopRequestsParams {
	return ImmutableGetDeniedShopRequestsParams{Proxy: wasmlib.NewParamsProxy()}
}

// ID of shop Owner
func (s ImmutableGetDeniedShopRequestsParams) ShopOwner() wasmtypes.ScImmutableAgentID {
	return wasmtypes.NewScImmutableAgentID(s.Proxy.Root(ParamShopOwner))
}

type MutableGetDeniedShopRequestsParams struct {
	Proxy wasmtypes.Proxy
}

// ID of shop Owner
func (s MutableGetDeniedShopRequestsParams) ShopOwner() wasmtypes.ScMutableAgentID {
	return wasmtypes.NewScMutableAgentID(s.Proxy.Root(ParamShopOwner))
}

type ImmutableGetErrorMessagesViewParams struct {
	Proxy wasmtypes.Proxy
}

func NewImmutableGetErrorMessagesViewParams() ImmutableGetErrorMessagesViewParams {
	return ImmutableGetErrorMessagesViewParams{Proxy: wasmlib.NewParamsProxy()}
}

// string of requestID
func (s ImmutableGetErrorMessagesViewParams) RequestID() wasmtypes.ScImmutableString {
	return wasmtypes.NewScImmutableString(s.Proxy.Root(ParamRequestID))
}

type MutableGetErrorMessagesViewParams struct {
	Proxy wasmtypes.Proxy
}

// string of requestID
func (s MutableGetErrorMessagesViewParams) RequestID() wasmtypes.ScMutableString {
	return wasmtypes.NewScMutableString(s.Proxy.Root(ParamRequestID))
}

type ImmutableGetOpenShopRequestParams struct {
	Proxy wasmtypes.Proxy
}

func NewImmutableGetOpenShopRequestParams() ImmutableGetOpenShopRequestParams {
	return ImmutableGetOpenShopRequestParams{Proxy: wasmlib.NewParamsProxy()}
}

// agendID of owner
func (s ImmutableGetOpenShopRequestParams) ShopOwner() wasmtypes.ScImmutableAgentID {
	return wasmtypes.NewScImmutableAgentID(s.Proxy.Root(ParamShopOwner))
}

type MutableGetOpenShopRequestParams struct {
	Proxy wasmtypes.Proxy
}

// agendID of owner
func (s MutableGetOpenShopRequestParams) ShopOwner() wasmtypes.ScMutableAgentID {
	return wasmtypes.NewScMutableAgentID(s.Proxy.Root(ParamShopOwner))
}

type ImmutableGetRegisteredShopsFromOwnerParams struct {
	Proxy wasmtypes.Proxy
}

func NewImmutableGetRegisteredShopsFromOwnerParams() ImmutableGetRegisteredShopsFromOwnerParams {
	return ImmutableGetRegisteredShopsFromOwnerParams{Proxy: wasmlib.NewParamsProxy()}
}

// agentID from owner
func (s ImmutableGetRegisteredShopsFromOwnerParams) ShopOwner() wasmtypes.ScImmutableAgentID {
	return wasmtypes.NewScImmutableAgentID(s.Proxy.Root(ParamShopOwner))
}

type MutableGetRegisteredShopsFromOwnerParams struct {
	Proxy wasmtypes.Proxy
}

// agentID from owner
func (s MutableGetRegisteredShopsFromOwnerParams) ShopOwner() wasmtypes.ScMutableAgentID {
	return wasmtypes.NewScMutableAgentID(s.Proxy.Root(ParamShopOwner))
}

type ImmutableGetShopStatisticsParams struct {
	Proxy wasmtypes.Proxy
}

func NewImmutableGetShopStatisticsParams() ImmutableGetShopStatisticsParams {
	return ImmutableGetShopStatisticsParams{Proxy: wasmlib.NewParamsProxy()}
}

// name of the shop
func (s ImmutableGetShopStatisticsParams) ShopName() wasmtypes.ScImmutableString {
	return wasmtypes.NewScImmutableString(s.Proxy.Root(ParamShopName))
}

type MutableGetShopStatisticsParams struct {
	Proxy wasmtypes.Proxy
}

// name of the shop
func (s MutableGetShopStatisticsParams) ShopName() wasmtypes.ScMutableString {
	return wasmtypes.NewScMutableString(s.Proxy.Root(ParamShopName))
}

type ImmutableGetSpecificProductsParams struct {
	Proxy wasmtypes.Proxy
}

func NewImmutableGetSpecificProductsParams() ImmutableGetSpecificProductsParams {
	return ImmutableGetSpecificProductsParams{Proxy: wasmlib.NewParamsProxy()}
}

// Name of Musician
func (s ImmutableGetSpecificProductsParams) ShopName() wasmtypes.ScImmutableString {
	return wasmtypes.NewScImmutableString(s.Proxy.Root(ParamShopName))
}

type MutableGetSpecificProductsParams struct {
	Proxy wasmtypes.Proxy
}

// Name of Musician
func (s MutableGetSpecificProductsParams) ShopName() wasmtypes.ScMutableString {
	return wasmtypes.NewScMutableString(s.Proxy.Root(ParamShopName))
}
