// Code generated by schema tool; DO NOT EDIT.

//go:build wasm
// +build wasm

package main

import (
	"test/go/russfestimpl"
	"github.com/iotaledger/wasp/packages/wasmvm/wasmvmhost/go/wasmvmhost"
)

func main() {
}

func init() {
	wasmvmhost.ConnectWasmHost()
}

//export on_call
func onCall(index int32) {
	russfestimpl.OnDispatch(index)
}

//export on_load
func onLoad() {
	russfestimpl.OnDispatch(-1)
}
