// Code generated by schema tool; DO NOT EDIT.

import * as wasmvmhost from 'wasmvmhost';
import * as sc from './russfestimpl';

export function on_call(index: i32): void {
    wasmvmhost.WasmVMHost.connect();
    sc.onDispatch(index);
}

export function on_load(): void {
    wasmvmhost.WasmVMHost.connect();
    sc.onDispatch(-1);
}
